//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneRandevuTakipOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int ID { get; set; }
        public Nullable<int> HastaID { get; set; }
        public string HastaTC { get; set; }
        public string HastaAd { get; set; }
        public string HastaSoyad { get; set; }
        public Nullable<int> DoktorID { get; set; }
        public string DoktorAd { get; set; }
        public string DoktorSoyad { get; set; }
        public Nullable<int> BolumID { get; set; }
        public string BolumAd { get; set; }
        public Nullable<System.DateTime> IslemTarih { get; set; }
        public Nullable<int> SaatID { get; set; }
        public Nullable<System.TimeSpan> RandevuSaat { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
        public virtual RandevuSaat RandevuSaat1 { get; set; }
    }
}
